### ISSUE TITLE
Drag and drop PDF functionality

### ISSUE THREAD

**Issue by histonemark** [jkitchin/org-ref#366]
First of all thank you for making this awesome package and making org-mode more compatible with science(tists). 
I find the package very useful but I have a little problem. Like you mention in the documentation, getting papers from some journals or publishers is difficult via the DOI approach (because of the varying ways in which they expand the url address to the full paper). This often results in failing download the paper automatically. But this is not much of a big deal for me, I can download it and drag and drop it to the bib file. What I don't understand is the functionality coded for this action, which is to open the PDF, get the DOI and add the Bibtex entry (fine!) and (try) to download another copy of the paper (!?). I would like org ref  to rename the paper according to the bibtex and put a copy of the PDF in the defined PDF folder. Is this possible? does it make sense?. I am sorry that my elisp is very limitted to mess in the code myself (which I tried).

Thank you very much!

**Comment by jkitchin** [comment]
That does make sense. i don't use this feature a lot, and the extra download was mostly laziness ;) I just pushed a commit that copies the pdf to the pdf-dir with the right name at least for when a single doi is found. If multiple dois are found, the old behavior is used, since there is no guarantee that the doi belongs to the pdf.

thanks for asking about this. It has been on my list for a long time!

**Comment by histonemark** [comment]
Wow! That was fast! Amazing. Thanks a lot!

**Comment by jkitchin** [comment]
Easy = fast ;)

**Comment by histonemark** [comment]
:)

**Comment by histonemark** [comment]
Unfortunately it does't work, when I drag the PDF it opens it with doc-view, doesn't add the bibtex entry  and does not copy the file. No error messages either. I tried to figure out why but I don't see the problem. Does it work for you?

Thanks!!

**Comment by jkitchin** [comment]
hm. It does work for me.

**Comment by histonemark** [comment]
I reinstalled everything and know dropping this [pdf](https://dl.dropboxusercontent.com/u/3975383/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf) to my references.bib correctly finds the DOI, adds the bibtex entry *but* fails to copy the pdf to the pdf folder. I see this error in *messages* buffer:
  **Wrong type argument: listp, "filion10_system_protein_locat_mappin_reveal"**

Almost there!!

Additional info: 
Emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.72) 
org-ref version: 20170105.1250

Again, thanks a ton!

**Comment by jkitchin** [comment]
ok, try one more pull. I found another issue with it that I think is fixed now.

**Comment by histonemark** [comment]
I tried with last Melpa version and it does the same, but your edit is more recent than the version update. I'll wait until the update to Melpa and tell you as soon as I test it.

**Comment by histonemark** [comment]
same error :( : Finds DOI, adds Bibtex entry and :
Contacting host: dx.doi.org:80
Title of the article (BibTeX converts it to lowercase)
Searched 1 buffer; 1 match for `[^[:ascii:]]'
**Wrong** type argument: listp, "filion10_system_protein_locat_mappin_reveal"**

**Comment by jkitchin** [comment]
I think this is related to the notes functionality. Try setting bibtex-completion-notes-path to a path. If you use a file, all notes will go in it I think. If it is a directory, the notes will be one org-file per entry.

you may also need the most up to date helm-bibtex. It seems the signature for the notes function changed to need a list. I guess you have an up to date version, since the error you got was about it not being a list.

**Comment by histonemark** [comment]
Doesn't solve the issue, I turned the debugger on and here is what I see:

Debugger entered--Lisp error: (wrong-type-argument listp "filion10_system_protein_locat_mappin_reveal")
  bibtex-completion-edit-notes("filion10_system_protein_locat_mappin_reveal")
  (lambda nil (bibtex-beginning-of-entry) (bibtex-completion-edit-notes (cdr (assoc "=key=" (bibtex-parse-entry)))))()
  doi-utils-insert-bibtex-entry-from-doi("10.1016/j.cell.2010.09.009")
  doi-utils-add-bibtex-entry-from-doi("10.1016/j.cell.2010.09.009" "/Users/mcorrales/Dropbox/Papers/references.bib")
  org-ref-pdf-dnd-protocol("file:///Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf" private)
  byte-code("\306\211\203%\n@\307	@\"\203	A\f\"\310\311\312\"\210\nA\211\204*\306\207" [dnd-protocol-alist bf --dolist-tail-- url action ret nil string-match throw done t] 4)
  dnd-handle-one-url(#<window 3 on references.bib> private "file:///Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf")
  mac-dnd-handle-pasteboard-filenames(#<window 3 on references.bib> private (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]))
  mac-dnd-drop-data((drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]))) #<frame Emacs@feather.local 0x105918250> #<window 3 on references.bib> (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]) "NSFilenamesPboardType" nil)
  mac-dnd-handle-drag-n-drop-event((drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]))))
  #<subr call-interactively>(mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))])
  ad-Advice-call-interactively(#<subr call-interactively> mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))])
  apply(ad-Advice-call-interactively #<subr call-interactively> (mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))]))
  call-interactively(mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))])
  command-execute(mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (333 . 440) 0 nil 1 (41 . 0) nil (333 . 440) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))] t)

But i dont find in the function bibtex-completion-edit-notes the place where it asks the list precate. I am sorry but this is far beyon my lisp abilities. Sorry to be annoying, but I see it so close :)

Thanks

**Comment by jkitchin** [comment]
What do you have the variable org-ref-notes-function set to?

**Comment by jkitchin** [comment]
The problem is bibtex-completion-edit-notes wants a list of keys as its argument, but somewhere it is getting only "filion10_system_protein_locat_mappin_reveal" which is a string, and so you get the wrong type argument error that you see.

**Comment by histonemark** [comment]
I have not touched it. Here it is:

Value: (lambda
  (thekey)
  (let*
      ((results
	(org-ref-get-bibtex-key-and-file thekey))
       (key
	(car results))
       (bibfile
	(cdr results)))
    (save-excursion
      (with-temp-buffer
	(insert-file-contents bibfile)
	(bibtex-set-dialect
	 (parsebib-find-bibtex-dialect)
	 t)
	(bibtex-search-entry key)
	(org-ref-open-bibtex-notes)))))

The string that you are refering to is the bibtex key resulting of the drag and drop of the article in my previous comment so it is passed by the org ref function as a string if i am not mistaken.

**Comment by jkitchin** [comment]
That is the bibtex key. What is happening for you is somewhere this is getting called:

(bibtex-completion-edit-notes "filion10_system_protein_locat_mappin_reveal")

which causes the error, because it should be:

(bibtex-completion-edit-notes '("filion10_system_protein_locat_mappin_reveal"))

I am not sure where that could be happening for you though.

**Comment by histonemark** [comment]
Yes I see but i still do'´t know who is calling bibtex-completion-edit-notes... because following your code:
**This gets done**.
((= 1 (length dois))
	    ;; we do not need to get the pdf, since we have one.
	    (let ((doi-utils-download-pdf nil))
	      (doi-utils-add-bibtex-entry-from-doi
	       (car dois)
	       (buffer-file-name))
**But this fails**:
;; we should copy the pdf to the pdf directory though
	      (let ((key (cdr (assoc "=key=" (bibtex-parse-entry)))))
	      	(copy-file path (expand-file-name (format "%s.pdf" key) org-ref-pdf-directory))))

Because the file is not copied. But the debuger error refers to bibtex-completion-edit-notes which i dont see where it is used/called.

**Comment by histonemark** [comment]
With the new Melpa update the error has changed. This one I think is easier to figure out: 
Debugger entered--Lisp error: (file-error "Opening input file" "no such file or directory" "/Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf")
  copy-file("///Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf" "/Users/mcorrales/Dropbox/Papers/filion10_system_protein_locat_mappin_reveal.pdf")
  org-ref-pdf-dnd-protocol("file:///Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf" private)
  byte-code("\306\211\203%\n@\307	@\"\203	A\f\"\310\311\312\"\210\nA\211\204*\306\207" [dnd-protocol-alist bf --dolist-tail-- url action ret nil string-match throw done t] 4)
  dnd-handle-one-url(#<window 3 on references.bib> private "file:///Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf")
  mac-dnd-handle-pasteboard-filenames(#<window 3 on references.bib> private (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]))
  mac-dnd-drop-data((drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]))) #<frame Emacs@feather.local 0x105918250> #<window 3 on references.bib> (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]) "NSFilenamesPboardType" nil)
  mac-dnd-handle-drag-n-drop-event((drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")]))))
  #<subr call-interactively>(mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))])
  ad-Advice-call-interactively(#<subr call-interactively> mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))])
  apply(ad-Advice-call-interactively #<subr call-interactively> (mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))]))
  call-interactively(mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))])
  command-execute(mac-dnd-handle-drag-n-drop-event nil [(drag-n-drop (#<window 3 on references.bib> 1 (563 . 513) 0 nil 1 (70 . 0) nil (563 . 513) (8 . 18)) (:type "NSFilenamesPboardType" :actions (delete move generic link copy) :data (array . [(string . "/Users/mcorrales/Desktop/Filion et al. - 2010 - Systematic protein location mapping reveals five principal chromatin types in Drosophila cells.pdf")])))] t)

You are triying to open the pdf with the name of the key without having renamed the file. Do you see what I mean?

**Comment by jkitchin** [comment]
No that error is because you have spaces in the filename, so the file /Users/mcorrales/Desktop/Filion%20et%20al.%20-%202010%20-%20Systematic%20protein%20location%20mapping%20reveals%20five%20principal%20chromatin%20types%20in%20Drosophila%20cells.pdf doesn't appear to exist. The path needs to be unescaped to turn them back into spaces. I pushed a commit for that just now.

**Comment by histonemark** [comment]
Nowww!!! Works perfectly! So many thanks. 

Marc

**Comment by jkitchin** [comment]
great! Hopefully this works for others better too!

**Comment by histonemark** [comment]
I bet it will!! Thanks again!
