### ISSUE TITLE
Glossary: preview when using external definitions

### ISSUE THREAD

**Issue by fleimgruber** [jkitchin/org-ref#587]
Given
```
#+latex_header: \newglossaryentry{computer}{name=computer,description={A machine}}

A gls:computer is good for computing.
```
when hovering the mouse over the `gls:computer` link a preview of the description is shown in the minibuffer.

This does not work however when using an external `glossary.tex` definitions file
```
#+latex_header: \loadglsentries[main]{glossary}
```

What are your thoughts on supporting this? For a file relative to the current Org mode file this should be straightforward, but the file could be somewhere in the TEXMF tree as well so that one would have to be looked up as well.

**Comment by jkitchin** [comment]
I don't have a particular need for it, but if you want to give it a shot I would look at a PR. It is pretty heavy on latex. It might be worthwhile thinking about how to make it more orgish. That is tough though, since the entries go in the latex header. It is hard to get that to work well with export.

**Comment by fleimgruber** [comment]
I would first try to understand the preview machinery that gets kicked off when hovering on a link - or even better: If point is somewhere on the visible link region. Without knowing too much about org-ref innards, I assumed this kind of preview would be independent of export.

**Comment by jkitchin** [comment]
Here is an example function that is triggered by the :help-echo that makes a tooltip:
https://github.com/jkitchin/org-ref/blob/master/org-ref-core.el#L1500

It is set on a link like this:
https://github.com/jkitchin/org-ref/blob/master/org-ref-core.el#L1762

The gist of these is you have to go to the position then build the string you want to show from the context you can get at that position. 

The current function that does this for glossary entries is at https://github.com/jkitchin/org-ref/blob/master/org-ref-glossary.el#L226.

This could be modified to look locally first, then in external files, for example.

**Comment by jkitchin** [comment]
The preview could be independent of export indeed. But, if you plan to do html export for example, you will have to use all the latex machinery and syntax to achieve that. That is what I meant by latex heavy. It would be nicer if the syntax was all org, and could be easily exported to latex or html, without requiring any latex. That might be too tall an order. I guess your main use is export to latex, so the current solution is lighter and more convenient than pure latex.

**Comment by fleimgruber** [comment]
Thanks for laying out the path and additional thoughts.
I tried to follow this mentally and then tried to debug `or-glossary-tooltip` with `(edebug-defun)` but that does not work on mouse hovering, it just displays the tooltip in the minibuffer.
Am I missing something about the way the function is registered with the rest via `:help-echo`?

**Comment by jkitchin** [comment]
I also cannot use debug for the tooltip function. I am not sure if there is some protective mechanism around that that prevents it perhaps. You can do it the old fashioned way with messages.

The reason you see it in the minibuffer must be that you tooltip-mode off. Otherwise, it should show at the point.

**Comment by jkitchin** [comment]
Alternatively, you can define this function:

```
(defun ogt ()
  (interactive)
  (or-glossary-tooltip nil nil (point)))
```

then use edebug-defun on or-glossary-tooltip

put point on your glossary link, and M-x ogt which should trigger a debug session on that function.

**Comment by darcamo** [comment]
Was there any advance on this? Is there still interest in an org-mode syntax approach. One possible solution with org-mode syntax could be defining a table like

```org
| Key  | Short | Long                           |
|------+-------+--------------------------------|
| MIMO |       | multiple-input multiple output |
| QOS  | QoS   | quality-of-service             |
| BB   |       | branch and bound               |
| ...  | ...   | ...                            |
```

This table would be set to not be exported by org and instead processed by org-ref, which would generate the `\newacronym` calls and add them in the preamble. unfortubately I don't know enough lisp for trying it myself. The user could create a table for glassary entries and another for acronym entries (which both use the glossaries package in latex). This would probably also make it easier to add functionality to the html export (maybe showing the tooltip with the glossary description or the acronym expansion on mouse hover).

**Comment by jkitchin** [comment]
That is a good idea. I don't personally have the time to work on this now. I like the idea of using a table for this with org-syntax.  It might be tricky to figure out how to keep it from exporting in org though, and to make it seen by org-ref while trying to keep to org ideas. one might put it in a specially tagged heading for example and use that tag to exclude it on export. I am less sure how to make it clear to org-ref it is a table to build definitions from, maybe a file keyword could declare the table name.

**Comment by darcamo** [comment]
The idea actually came from the [org-latex-subfigure](https://github.com/linktohack/ox-latex-subfigure) package, which uses a table as a way to create subfigures in latex export. Other export targets could just export the table as usual.

Using a table and whatever "tricks" the org-latex-subfigure author is using means that org-ref could intercept such a table in latex export to create the newglossaryentrynewacronym in latex export and maybe also do something in html export (to show tooltips on hover). Other export targets would just export the table as usual, which is actually not that bat.

**Comment by jagrg** [comment]
I also don't have much time to work on this, but I like the idea. I
suppose you can grab the definitions from the table and insert them
before parsing the export buffer. There's more that would need to be
changed (links for example won't work).

(defun glossaries (backend)
  (let (list)
    (when (org-export-derived-backend-p backend 'latex)
      (save-excursion
	(goto-char (point-min))
	(when (re-search-forward "#\\+name: acronym" nil t)
	  (forward-line 2)
	  (while (org-at-table-p)
	    (forward-line 1)
	    (let ((key (string-trim (org-table-get-field 1 nil)))
		  (short (string-trim (org-table-get-field 2 nil)))
		  (long (string-trim (org-table-get-field 3 nil)))
		  (re "#+latex_header_extra: \\newacronym{%s}{%s}{%s}\n"))
	      (unless (string= key "")
		(push (format re key short long) list))))
	  (goto-char (point-min))
	  (dolist (i list)
	    (insert i)))))))

(add-to-list 'org-export-before-parsing-hook 'glossaries)

A test file:

#+title: Test
#+latex_header: \usepackage{glossaries}
#+latex_header: \makeglossaries

First ac:bb. Second ac:bb. First ac:qos. Second ac:qos.

#+latex: \printglossaries

* Glossaries :noexport:

#+name: acronym
| Key  | Short | Long                           |
|------+-------+--------------------------------|
| mimo |       | multiple-input multiple output |
| qos  | QoS   | quality-of-service             |
| bb   | BB    | branch and bound               |

-- 
Jonathan

**Comment by jagrg** [comment]
I also don't have much time to work on this, but I like the idea. I
suppose you can grab the definitions from the table and insert them
before parsing the export buffer. There's more that would need to be
changed (links for example won't work).
```lisp
(defun glossaries (backend)
  (let (list)
    (when (org-export-derived-backend-p backend 'latex)
      (save-excursion
	(goto-char (point-min))
	(when (re-search-forward "#\\+name: acronym" nil t)
	  (forward-line 2)
	  (while (org-at-table-p)
	    (forward-line 1)
	    (when (org-at-table-p)
	      (let ((key (string-trim (org-table-get-field 1 nil)))
		    (short (string-trim (org-table-get-field 2 nil)))
		    (long (string-trim (org-table-get-field 3 nil)))
		    (string "#+latex_header_extra: \\newacronym{%s}{%s}{%s}\n"))
		(push (format string key short long) list))))
	  (goto-char (point-min))
	  (dolist (i list)
	    (insert i)))))))

(add-to-list 'org-export-before-parsing-hook 'glossaries)
```
A test file:
```
#+title: Test
#+latex_header: \usepackage{glossaries}
#+latex_header: \makeglossaries

First ac:bb. Second ac:bb. First ac:qos. Second ac:qos.

#+latex: \printglossaries

* Glossaries :noexport:

#+name: acronym
| Key  | Short | Long                           |
|------+-------+--------------------------------|
| mimo |       | multiple-input multiple output |
| qos  | QoS   | quality-of-service             |
| bb   | BB    | branch and bound               |
```

**Comment by japhir** [comment]
It would be great if these would also be used to find/replace the relevant calls in odt/html export. Should probably be implemented just before the fallback option implemented in https://github.com/jkitchin/org-ref/pull/412 by @jagrg.

But it may be difficult because we'd be taking over some of the computational steps from LaTeX, right?

**Comment by darcamo** [comment]
I  might be wrong, but it seems org-ref does nothing when exporting to html and we just get the link labels. 

I just found [this package](https://alhassy.github.io/org-special-block-extras/#Tooltips-for-Glossaries-Dictionaries-and-Documentation), which among other things has export for glossaries and usea links just like org-ref.

I'll investigate it when I have some time. It would be great if this functionality could be incorporated into org-ref.

**Comment by jkitchin** [comment]
> It would be great if these would also be used to find/replace the relevant calls in odt/html export. Should probably be implemented just before the fallback option implemented in #412 by @jagrg.
> 
> But it may be difficult because we'd be taking over some of the computational steps from LaTeX, right?

yes, this is basically replicating what LaTeX does. It might be doable here. It is hard to replicate bibtex! It would definitely involve some preprocessing hook functions.

**Comment by fleimgruber** [comment]
I just had another idea: could this be solved via a [#+SETUPFILE](https://orgmode.org/manual/In_002dbuffer-Settings.html)? I came up with this conversion function

```
(defun my-glossary-tex-to-org ()
  (interactive)
  (with-temp-file
      "glossary.org"
    (insert-file-contents "~/path/to/glossary.tex")
    (goto-char 1)
    (replace-regexp "^" "#+LATEX_HEADER: ")))
```

to keep the glossary master glossary.tex in sync with glossary.org that would be used in the org header as `#+SETUPFILE: glossary.org`. If `org-ref` would support parsing this file if it is given, then that should also work for export. @jkitchin do you think this is a good approach? Maybe `or-follow-glossary` could check for a `#+SETUPFILE` to do `re-search-forward` in as well? On a related note, I use the `\newacronym` from glossaries.tex, is this supported / could we support it easily?

**Comment by jkitchin** [comment]
I have implemented a lot of these ideas up to the external entry definitions and the table definitions. I haven't changed any of the other backend export functions.

**Comment by fleimgruber** [comment]
Thanks for implementing this! I just had a look and it seems that in `#+latex_header: \loadglsentries[main]{glossary}` the `glossary` is taken as a file name sans ".tex" relative or absolute to the .org file in

https://github.com/jkitchin/org-ref/blob/e43cdf00e7e2277e4534914c43af09757329ca21/org-ref-glossary.el#L169

but the glossary.tex file is inside a standard texmf tree on my system, so org-ref is not able to find the external .tex file as it resides in `~/texmf/tex/latex/misc/glossary.tex`. Is there a way for org-ref to look in texmf trees (without the whole LaTeX machinery you mentioned in earlier replies)? It works nicely if I use the full relative path or the absolute path to glossary.tex.

**Comment by jkitchin** [comment]
You can probably find it with `kpsewhere tex glossary`, although I am not sure what you should do if you get more than one result. If you run that command in a shell, do you get the more than one result?

**Comment by fleimgruber** [comment]
`kpsewhich tex glossary` returns the correct file and only that file.

**Comment by jkitchin** [comment]
see if c97f339 works for you.

**Comment by fleimgruber** [comment]
https://github.com/jkitchin/org-ref/commit/c97f339cac7f06a15930febde8c7f3a9f837eb4e works, but on Windows I get very bad performance for this, it seems that here

```
#+latex_header: \loadglsentries[main]{glossary}
#+latex_header: \newglossaryentry{computer}{name=computer,description={A machine}}

A gls:computer is good for computing. A gls:cmptr works too.
```

hovering on `gls:computer` starts `kpsewhich` as well (when I think it should not?) and on the external `gls:cmptr` it seems that `kpsewhich` gets called about 10 times or so (as gathered from visual inspection of task manager). I don't know whether that is Windows going crazy here or org-ref, I will try to profile or debug more.

**Comment by fleimgruber** [comment]
Tested on GNU/Linux as well, no performance problems there.

**Comment by jkitchin** [comment]
I guess this a current "feature" if you use external entries.Every time `or-parse-glossary-entry` is run, it will try to find the external file with kpsewhich. I don't see an easy way around that. Maybe it is a problem though because that function gets called in font-lock to calculate the faces so that if an entry is not defined it will be red. An easy test of that would be to define

```
(defun org-ref-glossary-face-fn (label)
  "Return a face for a glossary link."
  'org-ref-glossary-face)
```

which would avoid that. Does that make Windows performance a lot better?

**Comment by fleimgruber** [comment]
Unfortunately, I do not see a performance improvement with this. Could the external lookup be only run once on file load (and maybe on `M-x org-ctrl-c-ctrl-c` when on a header line) and the results be cached somehow? Sadly, spawning more than a few new processes quickly is really a pain on Windows.

**Comment by fleimgruber** [comment]
Otherwise, maybe the external lookup can be toggled via a user config setting? Performance is really unbearably bad and sometimes all babel source blocks are evaluated as well. I am at a loss as to why.

**Comment by jkitchin** [comment]
I guess your babel blocks are running because the search is done on an exported copy to allow for #+INCLUDE file (see issue #629 for example), but that should only happen when a value is not found any other way. It could be possible to let-bind a variable that would inhibit running org-blocks, since they do not need to be run for this.

I have implemented an idea for caching the kpsewhich output, and commented out the include code for now.

**Comment by fleimgruber** [comment]
I still see the described behavior with constantly spawned, killed and respawned `kpsewhich` processes.
